### ISSUE TITLE
Tab complete not working in rolling.

### ISSUE THREAD

**Issue by rshanor** [clearpathrobotics/nix-ros-base#7]
Hi, and thank you for putting this package together. 

I just watched your ROSCon video and decided to try out using ROS2 with Nix. I got as far as launching into a nix shell with `nix develop ros#rolling.ros_base.ws`. The ros2 CLI seemed to work, but I could not tab complete anything. Any idea how to fix this?

Much appreciated!

**Comment by mikepurvis** [comment]
Can you try sourcing these files?

```
source ~/.nix-profile/etc/profile.d/nix.sh
source ~/.nix-profile/share/bash-completion/completions/nix
```

That may only get you completions for the `nix` command, I know on the ROS 1 side almost all of the completion stuff comes from rosbash; I assume this was modularized in the ROS 2 world, but I'm not as familiar with it, unfortunately.
